# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c defaults -c conda-forge .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 35) %}
package:
  name: cugraph
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ git_revision_count }}

requirements:
  build:
    - cmake 3.12.4
    - python
    - cython=0.28.*
    - nvgraph {{ version }}
  run:
    - python
    - cython=0.28.*
    - nvgraph {{ version }}

about:
  home: http://rapids.ai/
  license: Apache 2.0
  license_file: LICENSE
  summary: cugraph Library
